"""Configuration and constants for the Telegram Bet Bot."""

import os
from dataclasses import dataclass
from typing import Final, Optional


@dataclass(frozen=True)
class Config:
    """Bot configuration loaded from environment variables."""

    telegram_token: str
    odds_api_key: Optional[str] = None
    espn_timeout: float = 10.0
    max_requests_per_minute: int = 10
    log_level: str = "INFO"

    @classmethod
    def from_env(cls) -> "Config":
        token = os.getenv("TELEGRAM_BOT_TOKEN", "")
        if not token:
            raise ValueError(
                "Missing TELEGRAM_BOT_TOKEN environment variable. "
                "Set it before running the bot."
            )
        return cls(
            telegram_token=token,
            odds_api_key=os.getenv("ODDS_API_KEY") or None,
            espn_timeout=float(os.getenv("ESPN_TIMEOUT", "10.0")),
            max_requests_per_minute=int(os.getenv("MAX_REQUESTS_PER_MINUTE", "10")),
            log_level=os.getenv("LOG_LEVEL", "INFO"),
        )


# ESPN API base URL template: sport_league -> URL
ESPN_SPORT_URLS: Final[dict[str, str]] = {
    "nba": "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard",
    "nfl": "https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard",
    "mlb": "https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard",
    "nhl": "https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/scoreboard",
    "ncaaf": "https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard",
    "ncaab": "https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard",
}

# The Odds API sport keys
ODDS_API_SPORTS: Final[dict[str, str]] = {
    "nba": "basketball_nba",
    "nfl": "americanfootball_nfl",
    "mlb": "baseball_mlb",
    "nhl": "icehockey_nhl",
    "ncaaf": "americanfootball_ncaaf",
    "ncaab": "basketball_ncaab",
}

# Bookmakers to query for CLV (in priority order)
# The Odds API keys: https://the-odds-api.com/sports-odds-data/bookmaker-apis.html
ODDS_API_BOOKMAKERS: Final[list[str]] = [
    "draftkings",
    "fanduel",
    "betmgm",
    "williamhill_us",  # Caesars
    "pointsbetus",
    "bovada",
    "barstool",
    "wynnbet",
    "betrivers",
]

# Friendly display names for bookmaker keys
BOOKMAKER_NAMES: Final[dict[str, str]] = {
    "draftkings": "DK",
    "fanduel": "FD",
    "betmgm": "MGM",
    "williamhill_us": "Caesars",
    "pointsbetus": "PB",
    "bovada": "Bovada",
    "barstool": "Barstool",
    "wynnbet": "Wynn",
    "betrivers": "Rivers",
}

# Sport aliases for detection
SPORT_ALIASES: Final[dict[str, str]] = {
    "nba": "nba",
    "basketball": "nba",
    "nfl": "nfl",
    "football": "nfl",
    "mlb": "mlb",
    "baseball": "mlb",
    "nhl": "nhl",
    "hockey": "nhl",
    "ncaaf": "ncaaf",
    "college football": "ncaaf",
    "ncaab": "ncaab",
    "college basketball": "ncaab",
}

# Comprehensive team aliases for fuzzy matching (NBA + other sports)
TEAM_ALIASES: Final[dict[str, str]] = {
    # Eastern Conference
    "atlanta hawks": "Atlanta Hawks",
    "hawks": "Atlanta Hawks",
    "atl": "Atlanta Hawks",
    "atlanta": "Atlanta Hawks",
    "boston celtics": "Boston Celtics",
    "celtics": "Boston Celtics",
    "bos": "Boston Celtics",
    "boston": "Boston Celtics",
    "brooklyn nets": "Brooklyn Nets",
    "nets": "Brooklyn Nets",
    "bkn": "Brooklyn Nets",
    "brooklyn": "Brooklyn Nets",
    "charlotte hornets": "Charlotte Hornets",
    "hornets": "Charlotte Hornets",
    "cha": "Charlotte Hornets",
    "charlotte": "Charlotte Hornets",
    "chicago bulls": "Chicago Bulls",
    "bulls": "Chicago Bulls",
    "chi": "Chicago Bulls",
    "chicago": "Chicago Bulls",
    "cleveland cavaliers": "Cleveland Cavaliers",
    "cavaliers": "Cleveland Cavaliers",
    "cavs": "Cleveland Cavaliers",
    "cle": "Cleveland Cavaliers",
    "cleveland": "Cleveland Cavaliers",
    "detroit pistons": "Detroit Pistons",
    "pistons": "Detroit Pistons",
    "det": "Detroit Pistons",
    "detroit": "Detroit Pistons",
    "indiana pacers": "Indiana Pacers",
    "pacers": "Indiana Pacers",
    "ind": "Indiana Pacers",
    "indiana": "Indiana Pacers",
    "miami heat": "Miami Heat",
    "heat": "Miami Heat",
    "mia": "Miami Heat",
    "miami": "Miami Heat",
    "milwaukee bucks": "Milwaukee Bucks",
    "bucks": "Milwaukee Bucks",
    "mil": "Milwaukee Bucks",
    "milwaukee": "Milwaukee Bucks",
    "new york knicks": "New York Knicks",
    "knicks": "New York Knicks",
    "ny": "New York Knicks",
    "nyk": "New York Knicks",
    "new york": "New York Knicks",
    "orlando magic": "Orlando Magic",
    "magic": "Orlando Magic",
    "orl": "Orlando Magic",
    "orlando": "Orlando Magic",
    "philadelphia 76ers": "Philadelphia 76ers",
    "76ers": "Philadelphia 76ers",
    "sixers": "Philadelphia 76ers",
    "phi": "Philadelphia 76ers",
    "philadelphia": "Philadelphia 76ers",
    "toronto raptors": "Toronto Raptors",
    "raptors": "Toronto Raptors",
    "tor": "Toronto Raptors",
    "toronto": "Toronto Raptors",
    "washington wizards": "Washington Wizards",
    "wizards": "Washington Wizards",
    "was": "Washington Wizards",
    "washington": "Washington Wizards",
    # Western Conference
    "dallas mavericks": "Dallas Mavericks",
    "mavericks": "Dallas Mavericks",
    "mavs": "Dallas Mavericks",
    "dal": "Dallas Mavericks",
    "dallas": "Dallas Mavericks",
    "denver nuggets": "Denver Nuggets",
    "nuggets": "Denver Nuggets",
    "den": "Denver Nuggets",
    "denver": "Denver Nuggets",
    "golden state warriors": "Golden State Warriors",
    "warriors": "Golden State Warriors",
    "gsw": "Golden State Warriors",
    "golden state": "Golden State Warriors",
    "gs": "Golden State Warriors",
    "houston rockets": "Houston Rockets",
    "rockets": "Houston Rockets",
    "hou": "Houston Rockets",
    "houston": "Houston Rockets",
    "la clippers": "LA Clippers",
    "clippers": "LA Clippers",
    "lac": "LA Clippers",
    "memphis grizzlies": "Memphis Grizzlies",
    "grizzlies": "Memphis Grizzlies",
    "mem": "Memphis Grizzlies",
    "memphis": "Memphis Grizzlies",
    "minnesota timberwolves": "Minnesota Timberwolves",
    "timberwolves": "Minnesota Timberwolves",
    "wolves": "Minnesota Timberwolves",
    "min": "Minnesota Timberwolves",
    "minnesota": "Minnesota Timberwolves",
    "new orleans pelicans": "New Orleans Pelicans",
    "pelicans": "New Orleans Pelicans",
    "nop": "New Orleans Pelicans",
    "new orleans": "New Orleans Pelicans",
    "oklahoma city thunder": "Oklahoma City Thunder",
    "thunder": "Oklahoma City Thunder",
    "okc": "Oklahoma City Thunder",
    "oklahoma city": "Oklahoma City Thunder",
    "phoenix suns": "Phoenix Suns",
    "suns": "Phoenix Suns",
    "phx": "Phoenix Suns",
    "phoenix": "Phoenix Suns",
    "portland trail blazers": "Portland Trail Blazers",
    "trail blazers": "Portland Trail Blazers",
    "blazers": "Portland Trail Blazers",
    "por": "Portland Trail Blazers",
    "portland": "Portland Trail Blazers",
    "sacramento kings": "Sacramento Kings",
    "kings": "Sacramento Kings",
    "sac": "Sacramento Kings",
    "sacramento": "Sacramento Kings",
    "san antonio spurs": "San Antonio Spurs",
    "spurs": "San Antonio Spurs",
    "sas": "San Antonio Spurs",
    "san antonio": "San Antonio Spurs",
    "utah jazz": "Utah Jazz",
    "jazz": "Utah Jazz",
    "uta": "Utah Jazz",
    "utah": "Utah Jazz",
    "los angeles lakers": "Los Angeles Lakers",
    "lakers": "Los Angeles Lakers",
    "lal": "Los Angeles Lakers",
    "la lakers": "Los Angeles Lakers",
    "arizona cardinals": "Arizona Cardinals",
    "cardinals": "St. Louis Cardinals",
    "ari": "Arizona Coyotes",
    "az cardinals": "Arizona Cardinals",
    "atlanta falcons": "Atlanta Falcons",
    "falcons": "Atlanta Falcons",
    "atl": "Atlanta Braves",
    "baltimore ravens": "Baltimore Ravens",
    "ravens": "Baltimore Ravens",
    "bal": "Baltimore Orioles",
    "blt": "Baltimore Ravens",
    "buffalo bills": "Buffalo Bills",
    "bills": "Buffalo Bills",
    "buf": "Buffalo Sabres",
    "carolina panthers": "Carolina Panthers",
    "panthers": "Florida Panthers",
    "car": "Carolina Hurricanes",
    "chicago bears": "Chicago Bears",
    "bears": "Chicago Bears",
    "chi": "Chicago Blackhawks",
    "cincinnati bengals": "Cincinnati Bengals",
    "bengals": "Cincinnati Bengals",
    "cin": "Cincinnati Reds",
    "cincy": "Cincinnati Bengals",
    "cleveland browns": "Cleveland Browns",
    "browns": "Cleveland Browns",
    "cle": "Cleveland Guardians",
    "dallas cowboys": "Dallas Cowboys",
    "cowboys": "Dallas Cowboys",
    "dal": "Dallas Stars",
    "denver broncos": "Denver Broncos",
    "broncos": "Denver Broncos",
    "den": "Denver Broncos",
    "detroit lions": "Detroit Lions",
    "lions": "Detroit Lions",
    "det": "Detroit Red Wings",
    "green bay packers": "Green Bay Packers",
    "packers": "Green Bay Packers",
    "gb": "Green Bay Packers",
    "green bay": "Green Bay Packers",
    "houston texans": "Houston Texans",
    "texans": "Houston Texans",
    "hou": "Houston Astros",
    "hst": "Houston Texans",
    "indianapolis colts": "Indianapolis Colts",
    "colts": "Indianapolis Colts",
    "ind": "Indianapolis Colts",
    "jacksonville jaguars": "Jacksonville Jaguars",
    "jaguars": "Jacksonville Jaguars",
    "jax": "Jacksonville Jaguars",
    "jac": "Jacksonville Jaguars",
    "kansas city chiefs": "Kansas City Chiefs",
    "chiefs": "Kansas City Chiefs",
    "kc": "Kansas City Royals",
    "kan": "Kansas City Royals",
    "las vegas raiders": "Las Vegas Raiders",
    "raiders": "Las Vegas Raiders",
    "lv": "Las Vegas Raiders",
    "lar": "Los Angeles Rams",
    "oak": "Oakland Athletics",
    "los angeles chargers": "Los Angeles Chargers",
    "chargers": "Los Angeles Chargers",
    "lac": "Los Angeles Chargers",
    "lach": "Los Angeles Chargers",
    "los angeles rams": "Los Angeles Rams",
    "rams": "Los Angeles Rams",
    "la rams": "Los Angeles Rams",
    "stl": "St. Louis Blues",
    "miami dolphins": "Miami Dolphins",
    "dolphins": "Miami Dolphins",
    "mia": "Miami Marlins",
    "miami": "Miami Dolphins",
    "minnesota vikings": "Minnesota Vikings",
    "vikings": "Minnesota Vikings",
    "min": "Minnesota Wild",
    "new england patriots": "New England Patriots",
    "patriots": "New England Patriots",
    "ne": "New England Patriots",
    "nwe": "New England Patriots",
    "new orleans saints": "New Orleans Saints",
    "saints": "New Orleans Saints",
    "no": "New Orleans Saints",
    "nor": "New Orleans Saints",
    "new york giants": "New York Giants",
    "giants": "San Francisco Giants",
    "nyg": "New York Giants",
    "new york jets": "New York Jets",
    "jets": "Winnipeg Jets",
    "nyj": "New York Jets",
    "philadelphia eagles": "Philadelphia Eagles",
    "eagles": "Philadelphia Eagles",
    "phi": "Philadelphia Flyers",
    "pittsburgh steelers": "Pittsburgh Steelers",
    "steelers": "Pittsburgh Steelers",
    "pit": "Pittsburgh Penguins",
    "san francisco 49ers": "San Francisco 49ers",
    "49ers": "San Francisco 49ers",
    "sf": "San Francisco Giants",
    "san francisco": "San Francisco 49ers",
    "seattle seahawks": "Seattle Seahawks",
    "seahawks": "Seattle Seahawks",
    "sea": "Seattle Kraken",
    "tampa bay buccaneers": "Tampa Bay Buccaneers",
    "buccaneers": "Tampa Bay Buccaneers",
    "bucs": "Tampa Bay Buccaneers",
    "tb": "Tampa Bay Lightning",
    "tennessee titans": "Tennessee Titans",
    "titans": "Tennessee Titans",
    "ten": "Tennessee Titans",
    "washington commanders": "Washington Commanders",
    "commanders": "Washington Commanders",
    "was": "Washington Capitals",
    "wsh": "Washington Nationals",
    "arizona diamondbacks": "Arizona Diamondbacks",
    "diamondbacks": "Arizona Diamondbacks",
    "dbacks": "Arizona Diamondbacks",
    "atlanta braves": "Atlanta Braves",
    "braves": "Atlanta Braves",
    "baltimore orioles": "Baltimore Orioles",
    "orioles": "Baltimore Orioles",
    "boston red sox": "Boston Red Sox",
    "red sox": "Boston Red Sox",
    "bos": "Boston Bruins",
    "chicago cubs": "Chicago Cubs",
    "cubs": "Chicago Cubs",
    "chicago white sox": "Chicago White Sox",
    "white sox": "Chicago White Sox",
    "chw": "Chicago White Sox",
    "cws": "Chicago White Sox",
    "cincinnati reds": "Cincinnati Reds",
    "reds": "Cincinnati Reds",
    "cleveland guardians": "Cleveland Guardians",
    "guardians": "Cleveland Guardians",
    "colorado rockies": "Colorado Rockies",
    "rockies": "Colorado Rockies",
    "col": "Colorado Avalanche",
    "detroit tigers": "Detroit Tigers",
    "tigers": "Detroit Tigers",
    "houston astros": "Houston Astros",
    "astros": "Houston Astros",
    "kansas city royals": "Kansas City Royals",
    "royals": "Kansas City Royals",
    "los angeles angels": "Los Angeles Angels",
    "angels": "Los Angeles Angels",
    "laa": "Los Angeles Angels",
    "la angels": "Los Angeles Angels",
    "los angeles dodgers": "Los Angeles Dodgers",
    "dodgers": "Los Angeles Dodgers",
    "lad": "Los Angeles Dodgers",
    "la dodgers": "Los Angeles Dodgers",
    "miami marlins": "Miami Marlins",
    "marlins": "Miami Marlins",
    "milwaukee brewers": "Milwaukee Brewers",
    "brewers": "Milwaukee Brewers",
    "mil": "Milwaukee Brewers",
    "minnesota twins": "Minnesota Twins",
    "twins": "Minnesota Twins",
    "new york mets": "New York Mets",
    "mets": "New York Mets",
    "nym": "New York Mets",
    "new york yankees": "New York Yankees",
    "yankees": "New York Yankees",
    "nyy": "New York Yankees",
    "yanks": "New York Yankees",
    "oakland athletics": "Oakland Athletics",
    "athletics": "Oakland Athletics",
    "as": "Oakland Athletics",
    "philadelphia phillies": "Philadelphia Phillies",
    "phillies": "Philadelphia Phillies",
    "pittsburgh pirates": "Pittsburgh Pirates",
    "pirates": "Pittsburgh Pirates",
    "san diego padres": "San Diego Padres",
    "padres": "San Diego Padres",
    "sd": "San Diego Padres",
    "sdp": "San Diego Padres",
    "san francisco giants": "San Francisco Giants",
    "sfg": "San Francisco Giants",
    "seattle mariners": "Seattle Mariners",
    "mariners": "Seattle Mariners",
    "st louis cardinals": "St. Louis Cardinals",
    "st. louis cardinals": "St. Louis Cardinals",
    "tampa bay rays": "Tampa Bay Rays",
    "rays": "Tampa Bay Rays",
    "texas rangers": "Texas Rangers",
    "rangers": "New York Rangers",
    "tex": "Texas Rangers",
    "texas": "Texas Rangers",
    "toronto blue jays": "Toronto Blue Jays",
    "blue jays": "Toronto Blue Jays",
    "tor": "Toronto Maple Leafs",
    "washington nationals": "Washington Nationals",
    "nationals": "Washington Nationals",
    "anaheim ducks": "Anaheim Ducks",
    "ducks": "Anaheim Ducks",
    "ana": "Anaheim Ducks",
    "arizona coyotes": "Arizona Coyotes",
    "coyotes": "Arizona Coyotes",
    "boston bruins": "Boston Bruins",
    "bruins": "Boston Bruins",
    "buffalo sabres": "Buffalo Sabres",
    "sabres": "Buffalo Sabres",
    "calgary flames": "Calgary Flames",
    "flames": "Calgary Flames",
    "cgy": "Calgary Flames",
    "carolina hurricanes": "Carolina Hurricanes",
    "hurricanes": "Carolina Hurricanes",
    "canes": "Carolina Hurricanes",
    "chicago blackhawks": "Chicago Blackhawks",
    "blackhawks": "Chicago Blackhawks",
    "colorado avalanche": "Colorado Avalanche",
    "avalanche": "Colorado Avalanche",
    "avs": "Colorado Avalanche",
    "columbus blue jackets": "Columbus Blue Jackets",
    "blue jackets": "Columbus Blue Jackets",
    "cbj": "Columbus Blue Jackets",
    "dallas stars": "Dallas Stars",
    "stars": "Dallas Stars",
    "detroit red wings": "Detroit Red Wings",
    "red wings": "Detroit Red Wings",
    "edmonton oilers": "Edmonton Oilers",
    "oilers": "Edmonton Oilers",
    "edm": "Edmonton Oilers",
    "florida panthers": "Florida Panthers",
    "fla": "Florida Panthers",
    "los angeles kings": "Los Angeles Kings",
    "kings": "Los Angeles Kings",
    "lak": "Los Angeles Kings",
    "la kings": "Los Angeles Kings",
    "minnesota wild": "Minnesota Wild",
    "wild": "Minnesota Wild",
    "montreal canadiens": "Montreal Canadiens",
    "canadiens": "Montreal Canadiens",
    "mtl": "Montreal Canadiens",
    "habs": "Montreal Canadiens",
    "nashville predators": "Nashville Predators",
    "predators": "Nashville Predators",
    "nsh": "Nashville Predators",
    "preds": "Nashville Predators",
    "new jersey devils": "New Jersey Devils",
    "devils": "New Jersey Devils",
    "nj": "New Jersey Devils",
    "njd": "New Jersey Devils",
    "new york islanders": "New York Islanders",
    "islanders": "New York Islanders",
    "nyi": "New York Islanders",
    "new york rangers": "New York Rangers",
    "nyr": "New York Rangers",
    "ottawa senators": "Ottawa Senators",
    "senators": "Ottawa Senators",
    "ott": "Ottawa Senators",
    "sens": "Ottawa Senators",
    "philadelphia flyers": "Philadelphia Flyers",
    "flyers": "Philadelphia Flyers",
    "pittsburgh penguins": "Pittsburgh Penguins",
    "penguins": "Pittsburgh Penguins",
    "pens": "Pittsburgh Penguins",
    "san jose sharks": "San Jose Sharks",
    "sharks": "San Jose Sharks",
    "sj": "San Jose Sharks",
    "sjs": "San Jose Sharks",
    "seattle kraken": "Seattle Kraken",
    "kraken": "Seattle Kraken",
    "krk": "Seattle Kraken",
    "st louis blues": "St. Louis Blues",
    "st. louis blues": "St. Louis Blues",
    "blues": "St. Louis Blues",
    "tampa bay lightning": "Tampa Bay Lightning",
    "lightning": "Tampa Bay Lightning",
    "tbl": "Tampa Bay Lightning",
    "toronto maple leafs": "Toronto Maple Leafs",
    "maple leafs": "Toronto Maple Leafs",
    "leafs": "Toronto Maple Leafs",
    "utah hockey club": "Utah Hockey Club",
    "utah hc": "Utah Hockey Club",
    "vancouver canucks": "Vancouver Canucks",
    "canucks": "Vancouver Canucks",
    "van": "Vancouver Canucks",
    "vegas golden knights": "Vegas Golden Knights",
    "golden knights": "Vegas Golden Knights",
    "vgk": "Vegas Golden Knights",
    "vegas": "Vegas Golden Knights",
    "washington capitals": "Washington Capitals",
    "capitals": "Washington Capitals",
    "caps": "Washington Capitals",
    "winnipeg jets": "Winnipeg Jets",
    "wpg": "Winnipeg Jets",
}
